# Generated by Django 4.2.1 on 2023-05-10 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(max_length=100)),
                ('descripcion', models.TextField(max_length=300)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('modelo', models.TextField(max_length=100)),
                ('marca', models.TextField(max_length=100)),
                ('codigo', models.IntegerField()),
                ('stock', models.IntegerField()),
            ],
        ),
    ]
